name: MLflow Retraining CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install MLflow & Dependencies
        run: |
          # Memastikan semua dependensi yang dibutuhkan modelling.py terinstall
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Run MLflow Project (Retraining)
        run: |
          # Menjalankan project dari root repository. 
          # Pastikan folder 'MLProject' berisi file 'MLProject' (tanpa ekstensi) dan 'modelling.py'
          mlflow run MLProject --no-conda